import {
	blockUserResolver,
	createAdminResolver,
	unblockUserResolver,
	userResolver,
	usersResolver,
	resetPasswordResolver,
	sendChangeEmailOTPResolver,
	updateEmailResolver,
	updateUserResolver,
	productsResolver,
	updateProductResolver,
	createProductResolver,
	productResolver,
	readMessagesResolver,
	removeToCartResolver,
	sendMessageResolver,
	adminMessagesResolver,
	messageSentSubscription,
	addToCartResolver,
	readBouquetItemResolver,
	readAllBouquetItemsResolver,
	createBouquetItemResolver,
	updateBouquetItemResolver,
	readOrdersResolver,
	createCheckoutSessionResolver,
	readOrdersByUserResolver,
	updateOrderResolver,
	createOrderResolver,
	readMonthlyRevenueResolver,
	readLastMonthDataResolver,
	readBestSellingProductResolver,
	readProductsSummaryResolver,
	readOrdersSummaryResolver,
	notificationSentSubscription,
	unReviewedProductsResolver,
	checkoutCustomizeBouquetResolver,
} from "./resolvers/index.js";
import {
	deleteNotificationResolver,
	readNotificationsResolver,
	updateNotificationResolver,
} from "./resolvers/notification-resolver.js";
import { createReviewResolver } from "./resolvers/review-resolver.js";
import {
	readSettingsResolver,
	settingsResolver,
} from "./resolvers/settings-resolver.js";

export const resolvers = {
	Subscription: {
		messageSent: messageSentSubscription,
		notificationSent: notificationSentSubscription,
	},
	Query: {
		user: userResolver,
		users: usersResolver,
		product: productResolver,
		products: productsResolver,
		readMessages: readMessagesResolver,
		adminMessages: adminMessagesResolver,
		bouquetItems: readAllBouquetItemsResolver,
		bouquetItem: readBouquetItemResolver,
		orders: readOrdersResolver,
		readOrdersByUser: readOrdersByUserResolver,
		readMonthlyRevenue: readMonthlyRevenueResolver,
		lastMonthData: readLastMonthDataResolver,
		readBestSellingProducts: readBestSellingProductResolver,
		productsSummary: readProductsSummaryResolver,
		ordersSummary: readOrdersSummaryResolver,
		readNotifications: readNotificationsResolver,
		unReviewedProducts: unReviewedProductsResolver,
		readSettings: readSettingsResolver,
	},
	Mutation: {
		createAdmin: createAdminResolver,
		blockUser: blockUserResolver,
		unblockUser: unblockUserResolver,
		resetPassword: resetPasswordResolver,
		sendChangeEmailOTP: sendChangeEmailOTPResolver,
		updateEmail: updateEmailResolver,
		updateUser: updateUserResolver,
		createProduct: createProductResolver,
		updateProduct: updateProductResolver,
		removeToCart: removeToCartResolver,
		sendMessage: sendMessageResolver,
		addToCart: addToCartResolver,
		createBouquetItem: createBouquetItemResolver,
		updateBouquetItem: updateBouquetItemResolver,
		createCheckoutSession: createCheckoutSessionResolver,
		updateOrder: updateOrderResolver,
		createOrder: createOrderResolver,
		updateNotification: updateNotificationResolver,
		deleteNotification: deleteNotificationResolver,
		createReview: createReviewResolver,
		createCustomBouquet: checkoutCustomizeBouquetResolver,
		configureStore: settingsResolver,
	},
	// Mutation: {},
};
