import {
	blockUserResolver,
	createAdminResolver,
	unblockUserResolver,
	userResolver,
	usersResolver,
	resetPasswordResolver,
	sendChangeEmailOTPResolver,
	updateEmailResolver,
	updateUserResolver,
	productsResolver,
	updateProductResolver,
	createProductResolver,
	productResolver,
	readMessagesResolver,
	removeToCartResolver,
	sendMessageResolver,
	adminMessagesResolver,
	messageSentSubscription,
	addToCartResolver,
	readBouquetItemResolver,
	readAllBouquetItemsResolver,
	createBouquetItemResolver,
	updateBouquetItemResolver,
} from "./resolvers/index.js";

export const resolvers = {
	Subscription: {
		messageSent: messageSentSubscription,
	},
	Query: {
		user: userResolver,
		users: usersResolver,
		product: productResolver,
		products: productsResolver,
		readMessages: readMessagesResolver,
		adminMessages: adminMessagesResolver,
		bouquetItems: readAllBouquetItemsResolver,
		bouquetItem: readBouquetItemResolver,
	},
	Mutation: {
		createAdmin: createAdminResolver,
		blockUser: blockUserResolver,
		unblockUser: unblockUserResolver,
		resetPassword: resetPasswordResolver,
		sendChangeEmailOTP: sendChangeEmailOTPResolver,
		updateEmail: updateEmailResolver,
		updateUser: updateUserResolver,
		createProduct: createProductResolver,
		updateProduct: updateProductResolver,
		removeToCart: removeToCartResolver,
		sendMessage: sendMessageResolver,
		addToCart: addToCartResolver,
		createBouquetItem: createBouquetItemResolver,
		updateBouquetItem: updateBouquetItemResolver,
	},
	// Mutation: {},
};
